INTERNAL: save configuration instance in ArcusCache
naver/arcus-spring pull request #100
Opened 2024-09-05 08:00 UTC by oliviarla

### 🔗 Related Issue

- https://github.com/naver/arcus-spring/issues/65

### ⌨️ What I did

- 인자가 없는 생성자를 deprecate 시켜 사용하지 않도록 권장합니다. 대신 필수 인자를 입력해야 하는 생성자를 제공합니다.
- 반드시 내부에서만 사용되어야 하는 필드인 keyLockProvider를 제외하고는 모두 configuration을 통해 접근하도록 변경했습니다.
- 이를 통해 필수 인자가 아닌 옵션들의 검증은 ArcusConfiguration 한 군데에서만 거치면 됩니다. setter, getter도 ArcusCache 클래스에서 제공해줄 필요가 없습니다.
- 참고로 redis, couchbase도 XXXCache 클래스에 XXXCacheConfiguration 클래스를 필드로 두고 있습니다.

2024-09-05 09:39 UTC, uhm0311 commented on src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
>    }
Deprecated가 없습니다.
모든 Getter에 붙이려는 게 아닌가요?

2024-09-05 09:39 UTC, uhm0311 commented on src/test/resources/arcus_spring_arcusCache_test.xml
> +          p:prefix="testService-"/>
여기도 변경해야 하나요?

2024-09-05 10:47 UTC, oliviarla commented on src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
>    }
어떤 메서드 말씀하시는건가요?

2024-09-05 10:49 UTC, oliviarla commented on src/test/resources/arcus_spring_arcusCache_test.xml
> +          p:prefix="testService-"/>
기존대로 수정했습니다.

2024-09-06 01:40 UTC, uhm0311 commented on src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
>    }
`ArcusCache.getServiceId()`에 `@Deprecated`가 붙어 있지 않습니다.

2024-09-06 01:43 UTC, oliviarla commented on src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
>    }
362 라인에 붙어있습니다.

2024-09-06 02:17 UTC, jhpark816 reviewed
리뷰 완료

2024-09-06 02:17 UTC, jhpark816 commented on src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
> +  /**
여기 위에 empty line 추가하시죠.

2024-09-06 02:22 UTC, oliviarla commented on src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
> +  /**
추가했습니다.

2024-09-06 02:23 UTC, jhpark816 approved these changes

2024-09-06 02:45 UTC, jhpark816 commented
@uhm0311 최종 리뷰 바랍니다.

2024-09-06 02:51 UTC, uhm0311 requested changes

2024-09-06 02:51 UTC, uhm0311 commented on src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
> +    this.configuration = new ArcusCacheConfiguration();
`this(name, clientPool, new ArcusCacheConfiguration())`로 축약합시다.

2024-09-06 02:51 UTC, uhm0311 commented on src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
> +    Assert.notNull(cacheConfig);
null일때 출력할 메세지를 입력하지 않으면 Spring Framework 6와 호환이 되지 않습니다.
https://github.com/naver/arcus-spring/pull/63/files

2024-09-06 02:51 UTC, uhm0311 commented on src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
> +    Assert.notNull(keyLockProvider);
여기도 필요합니다.

2024-09-06 02:51 UTC, uhm0311 commented on src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
> +            configuration.getPrefix() : name);
String serviceId 변수와 String prefix 변수를 두어 담아두었다가 사용합시다.

2024-09-06 02:51 UTC, uhm0311 commented on src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
> +    Assert.notNull(operationTranscoder);
여기도 메세지가 필요합니다.

2024-09-06 02:51 UTC, uhm0311 commented on src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
> +    Assert.notNull(prefix);
여기도 메세지가 필요합니다.

2024-09-06 02:51 UTC, uhm0311 commented on src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
> +    Assert.notNull(arcusFrontCache);
여기도 메세지가 필요합니다.

2024-09-06 02:54 UTC, oliviarla commented on src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
> +    this.configuration = new ArcusCacheConfiguration();
super 와 this 모두 생성자 맨 첫줄에 위치해야 하므로 함께 사용할 수가 없습니다.

2024-09-06 02:55 UTC, uhm0311 commented on src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
> +    this.configuration = new ArcusCacheConfiguration();
super까지 포함해서 축약할 수 있지 않나요?

2024-09-06 03:07 UTC, oliviarla commented on src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
> +            configuration.getPrefix() : name);
getPrefixString 메서드 등 전체적으로 get 하여 null 체크를 한 후 다시 get하는 형태를 사용하고 있어 여기만 변경하면 조금 이상할 것 같습니다. 전체적으로 변경할까요?

2024-09-06 03:10 UTC, uhm0311 commented on src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
> +            configuration.getPrefix() : name);
어떤 의미인지 잘 모르겠습니다.
저는 아래의 코드가 되길 원했습니다.

```java
String serviceId = configuration.getServiceId();
String prefix = configuration.getPrefix();
String arcusPrefix = serviceId + ((prefix != null) ? prefix : name);
```

2024-09-06 03:16 UTC, oliviarla commented on src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
> +            configuration.getPrefix() : name);
여기를 말씀하신대로 변경하게 되면 아래와 같은 코드들도 전체적으로 바뀌어야 일관적이라는 의미였습니다. 일단 to be가 가독성이 더좋아보여서 전체적으로 변경해보겠습니다.
```java
// as is
if (configuration.getPrefix() != null) {
  return configuration.getServiceId() + configuration.getPrefix() + ":";
}
return configuration.getServiceId() + name + ":";

// to be
String serviceId = configuration.getServiceId();
String prefix = configuration.getPrefix();
return serviceId + ((prefix != null) ? prefix : name) + ":";
```

2024-09-06 03:20 UTC, oliviarla commented on src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
> +            configuration.getPrefix() : name);
이 부분 반영했고, 2회 이상 사용되는 값들은 configuration으로부터 get한 후 변수를 담아두도록 수정했습니다.

2024-09-06 03:26 UTC, uhm0311 approved these changes

2024-09-06 03:33 UTC, merged