DOC: Add user guide.
naver/arcus-spring pull request #59
Opened 2023-11-03 05:26 UTC by uhm0311

https://github.com/naver/arcus-spring/issues/58

사용자 가이드 문서를 작성했습니다.
`01-arcus-cloud-basics.md` 파일은 arcus-java-client에서 가져왔습니다.

https://github.com/uhm0311/arcus-spring/tree/uhm0311/develop3/docs

위 링크로 들어가서 문서를 보면 보기 쉽습니다.

2023-11-03 05:30 UTC, jhpark816 commented
@oliviarla @brido4125 리뷰 하시죠.

2023-11-03 06:30 UTC, brido4125 commented on docs/01-arcus-cloud-basics.md
> +이러한 cache item을 sticky item이라 하며, expiration time을 -1로 설정하면 된다.
expire time을 0으로 설정하는 경우도 설명에 넣으면 좋지 않을까요?

2023-11-03 06:30 UTC, brido4125 commented on docs/02-arcus-spring.md
> +캐시 아이템을 조회할 때 Front Cache에서 먼저 조회하여 캐시 응답성을 높인다.
Front Cache를 사용할 경우 여러 WAS간의 데이터 정합성이 불일치할 수 있다는 점을 넣는건 어떠신가요?
그래서 변경 되지 않는 값이나 굉장히 짧은 expire time을 설정해야한다는 코멘트도 있으면 좋을 것 같습니다.

2023-11-03 06:33 UTC, uhm0311 commented on docs/02-arcus-spring.md
> +캐시 아이템을 조회할 때 Front Cache에서 먼저 조회하여 캐시 응답성을 높인다.
비슷한 내용이 forceFrontCaching 부분에 있습니다.

2023-11-03 06:52 UTC, uhm0311 commented
@brido4125 

리뷰 반영했습니다.

2023-11-03 09:46 UTC, oliviarla requested changes
일부 리뷰했습니다.

2023-11-03 09:46 UTC, oliviarla commented on docs/02-arcus-spring.md
> +
"캐싱 기능을 이용하려면 아래와 같이 어노테이션을 사용하거나, 직접 CacheManager를 주입받아 사용할 수 있다."
언급해주면 좋겠습니다. 지금은 부연 설명 없이 코드만 있어서 처음 사용자는 이해하기 어려울 수도 있을 것 같네요..

그리고 가능하다면, 어떤 경우에 CacheManager를 직접 주입받아서 사용하는지 적어주면 좋을 것 같습니다.

2023-11-03 09:46 UTC, oliviarla commented on docs/02-arcus-spring.md
> +
ArcusCacheConfiguration 에서 설정 가능한 속성들(특히 serviceId, timeoutMilliSeconds, ...)에 대한 설명이 추가되면 좋겠습니다.

2023-11-03 09:46 UTC, oliviarla commented on docs/02-arcus-spring.md
> +ARCUS Spring에서 제공하는 KeyGenerator 구현체는 2가지가 있다.
KeyGenerator를 제공하는 이유도 적어주면 사용자들이 이해하기 편할 것 같습니다. ex) Cacheable의 key를 사용하는 것보다 좋은점이 있는지?

2023-11-03 09:46 UTC, oliviarla commented on docs/02-arcus-spring.md
> +- StringKeyGenerator: SimpleStringKeyGenerator의 문자열 생성 로직에 더해, 캐시 키로 사용할 수 없는 문자열을 제거하고, 캐시 대상 메소드의 매개변수의 해시 값을 맨 뒤에 붙인다.
두 KeyGenerator에서 어떤 것을 더 권장하는지에 대한 내용도 다루면 좋을 것 같습니다.
제생각에는 StringKeyGenerator을 사용하는 것이 의도치 않은 동작(ex. 캐시 키에 공백이 들어가 예외 발생)을 막을 수 있기 때문에 좋지 않나 싶습니다.

2023-11-03 09:46 UTC, oliviarla commented on docs/02-arcus-spring.md
> +#### Front Cache
h3 사이즈로 두어야 하지 않나요?
cacheable, cachemanager는 캐싱을 하는 방법을 알려주는 것이고, 이 내용은 독립적인 개념 소개라 h4 사이즈로 두는게 어색합니다.

2023-11-03 12:32 UTC, uhm0311 commented on docs/02-arcus-spring.md
> +
어떤 경우에 하는지는 사용자가 정의하기 나름이고, 어떤 사용 환경에서 사용하는지는 저도 잘 모르겠습니다.

2023-11-03 12:44 UTC, uhm0311 commented
@oliviarla 

리뷰 반영했습니다.

2023-11-03 13:34 UTC, uhm0311 commented
@jhpark816 

리뷰 반영했습니다.

2023-11-06 02:41 UTC, jhpark816 commented
@brido4125 @oliviarla 
다시 리뷰 바랍니다.

2023-11-06 03:05 UTC, brido4125 approved these changes

2023-11-06 03:24 UTC, oliviarla commented on docs/02-arcus-spring.md
> +public class ArcusConfiguration extends CachingConfigurerSupport {
Spring 6.0 버전에서 CachingConfigurerSupport 클래스가 Deprecated 되어, 단순히 keyGenerator나 cacheManager를 빈으로 등록만 해주어도 사용가능합니다.
CachingConfigurerSupport 클래스를 상속받지 않는 Config 예제도 함께 제공하면 어떨까요?

2023-11-06 03:24 UTC, oliviarla commented on docs/03-arcus-spring-notes.md
> +이러한 현상을 피하기 위해서는 SimpleStringKeyGenerator를 사용해야 한다.
두번째 문서에서 SimpleStringKeyGenerator는 하위호환성을 위해 남겨둔 클래스이라고 하셔서 StringKeyGenerator 사용을 권장하는게 좋을 것 같습니다.

2023-11-06 03:46 UTC, uhm0311 commented on docs/03-arcus-spring-notes.md
> +이러한 현상을 피하기 위해서는 SimpleStringKeyGenerator를 사용해야 한다.
hash 값을 피하고자 했던 사례가 네이버에 있었기 때문에 이 경우에 한해 SimpleStringKeyGenerator를 사용해야 한다고 하는 것입니다.

2023-11-06 03:55 UTC, uhm0311 commented on docs/02-arcus-spring.md
> +public class ArcusConfiguration extends CachingConfigurerSupport {
해당 예시는 `extends CachingConfigurerSupport` 구문 제외하고 다 동일할 거라서 주석으로 추가했습니다.

2023-11-07 10:11 UTC, uhm0311 commented
오프라인 리뷰 반영했습니다.

2023-11-15 02:52 UTC, jhpark816 commented
@oliviarla 리뷰를 완료하고 나면, approve 처리해 주세요.

2023-11-17 07:08 UTC, jhpark816 reviewed
일부 리뷰

2023-11-17 07:08 UTC, jhpark816 commented on docs/02-arcus-spring.md
> +- setTimeoutMilliSeconds(): ARCUS Java Client의 비동기 연산에서 사용할 Timeout을 Milliseconds 단위로 설정한다. 지정하지 않을 경우 700ms로 정해진다.
데이터 기준으로 그 개념을 설명하고,
이를 설정, 조회하는 메소드를 포함하여 설명하면 될 것 같습니다.

즉, 아래 형태로 설명하면 좋겠습니다.
- serviceId
  - 설명 1
  - 설명 2
- prefix
- expireSeconds
- timeoutMilliSeconds

2023-11-17 07:08 UTC, jhpark816 commented on docs/02-arcus-spring.md
> +  - 생성되는 문자열에 " "이 없어 ARCUS Cache의 키로 사용하기 적합하며, hash 값이 붙어 매개변수 조합마다 유일한 문자열을 생성하므로 일반적으로 가장 적합한 구현체이다.
ArcusCacheConfiguration, ArcusCacheManager, KeyGenerator를
**ARCUS Spring 기본 사용법** 이전에 설명하는 것은 어떤가요?

2023-11-17 07:08 UTC, jhpark816 commented on docs/02-arcus-spring.md
> +ARCUS Spring에서 제공하는 KeyGenerator 구현체는 2가지가 있다.
key generator는 아래 관점이 포함되어야 합니다.
- Default key generator : keyGenerator bean 설정하지 않았을 경우
- 2가지 key generator
- 2가지 key generator 사용하더라도, 최종 키가 어떤 경우에 변경될 수 있고, 어떻게 변경되는 지를 설명

2023-11-17 07:08 UTC, jhpark816 commented on docs/02-arcus-spring.md
> +- 캐시 키의 길이가 250자를 넘으면, KeyGenerator로 생성한 문자열을 MD5 Hash 값을 취하여 16진수 문자열로 만들고 캐시 키의 Prefix와 합쳐 캐시 키로 사용한다.
이 내용은 ArcusCacheConfiguration에서 다루어야 할 듯.

2023-11-17 09:02 UTC, uhm0311 commented
@jhpark816 

리뷰 반영했습니다.
파일을 3개로 나누던 것을, 개념에 대한 설명과 사용 예시에 대한 설명을 다시 나눠, 총 4개로 나누도록 변경했습니다.

2023-11-17 09:36 UTC, jhpark816 reviewed
일부 리뷰

2023-11-17 09:36 UTC, jhpark816 commented on docs/02-arcus-spring-concept.md
> +  - [1장의 Expiration Time 설명](01-arcus-cache-basics.md#expiration-eviction)을 참고하여 필수적으로 지정해야 한다.
지정하지 않으면 디폴트로 어떤 값으로 지정되지 않나요?

2023-11-17 09:39 UTC, uhm0311 commented on docs/02-arcus-spring-concept.md
> +  - null이 아닌 값을 필수적으로 지정해야 한다.
ArcusCache 클래스 단에서 serviceId 설정되어 있지 않으면 Exception 던지게 되어 있습니다.

2023-11-17 09:47 UTC, uhm0311 commented
@jhpark816 

리뷰 반영했습니다.

2023-11-17 12:00 UTC, jhpark816 reviewed
일부 리뷰

2023-11-17 12:00 UTC, jhpark816 commented on docs/02-arcus-spring-concept.md
> +이는 ARCUS Spring에서 제공하는 KeyGenerator를 사용해도, 다른 KeyGenerator를 사용해도 적용된다.
위의 내용도 아래와 같이 수정하였으면 합니다.
내용 검토하고, 수정이 필요하면 적절히 수정해도 됩니다.
----------------------

[ARCUS 캐시 키]는 공백(` `) 문자를 허용하지 않으며,  최대 길이가 250인 제약을 초기에 가지고 있었다. 이러한 제약을 준수하기 위하여, ARCUS Spring은 캐시 키를 생성할 시에 아래와 같이 처리하고 있음을 주의하여야 한다.
- ARCUS Spring에서 제공하는 2가지 KeyGenerator가 아닌 다른 KeyGenerator를 사용할 경우, 캐시 키가 예상과 다르게 생성될 수 있다.
   - KeyGenerator로 생성된 문자열에 ` ` 문자가 있다면 `_` 문자로 변환하며, 항상 원래 문자열의 해시 값을 구하여 문자열 뒤에 붙인다.
   - 해시 값을 붙이는 이유는 ` ` 문자가 `_` 문자로 변환된 경우와 원래 `_` 문자가 있던 경우를 구분할 수 있는 키를 생성하기 위함이다. 
   - 해시 값을 붙이는 다른 이유는 KeyGenerator의 리턴 객체가 서로 다름에도 동일한 키 문자열이 생성될 수 있는 가능성을 완전히 차단하기 위함이다.
- 캐시 키의 전체 길이가 250자를 넘는다면, KeyGenerator로 생성한 문자열을 MD5 Hash 값을 취하여 16진수 문자열로 만들고 이를 키 문자열로 사용한다. 이는 ARCUS Spring에서 제공하는 KeyGenerator를 사용하거나 다른 KeyGenerator를 사용하는 경우 모두에 적용된다.

[ARCUS 캐시 키]는 prefix 문자열과 subkey 문자열로 구성되며, 이를 콜론(':') 문자로 연결하여 생성한다. 캐시 키의 Prefix 문자열은 ArcusCacheConfiguration 객체로 생성하는 ArcusCache 객체의  serviceId과 prefix 또는 cacheName 조합으로 구성되고, subkey 문자열은 keyGenerator로 생성된다. 따라서, 최종적으로 만들어지는 ARCUS 캐시 키는 아래 형태와 같다.
- `<serviceId><prefix | cacheName>:<stringOfKeyGenerator>`

2023-11-20 02:36 UTC, uhm0311 commented
@jhpark816 

내용 일부 수정하여 반영했습니다.

> 해시 값을 붙이는 다른 이유는 KeyGenerator의 리턴 객체가 서로 다름에도 동일한 키 문자열이 생성될 수 있는 가능성을 완전히 차단하기 위함이다.

해시 값을 Object.hashcode()를 사용하는 것이 아니라, light_hash(Object.toString())를 사용하는 것이기 때문에 서로 다른 객체여도 toString()의 결과가 같으면 서로 같은 캐시 키가 생성되므로 내용에서 완전히 제외했습니다.

2023-11-20 07:20 UTC, jhpark816 reviewed
리뷰 완료

2023-11-20 07:20 UTC, jhpark816 commented on docs/03-arcus-spring-usage.md
> +캐싱 기능을 사용하려면 아래와 같이 `@Cacheable` 어노테이션을 사용하거나, CacheManager를 직접 주입 받아 사용할 수 있다.
@Cacheable 어노테이션을 사용하는 예시들만을 설명하고,

CacheManager 직접 주입 받아 사용하는 경우는 예시 1개만 간단히 설명하지 되지 않나 생각해요.

2023-11-20 08:17 UTC, uhm0311 commented
@jhpark816 

리뷰 반영했습니다.

2023-11-21 01:40 UTC, jhpark816 reviewed
리뷰 완료

2023-11-21 01:40 UTC, jhpark816 commented on docs/03-arcus-spring-usage.md
> +WebFlux와 ARCUS Spring을 함께 사용한다면 CacheManager를 주입 받아 캐시 아이템을 조회하고, 이를 Mono나 Flux로 감싸는 방식으로 활용이 가능하다.
> 대표적으로, ARCUS Spring이 아직 지원하지 않는 WebFlux 기능을 사용할 때가 있다.

> WebFlux와 ARCUS Spring을 함께 사용한다면 CacheManager를 주입 받아 캐시 아이템을 조회하고, 이를 Mono나 Flux로 감싸는 방식으로 활용이 가능하다.

이 문구는 제거하는 것이 좋겠습니다.

2023-11-21 01:40 UTC, jhpark816 commented on docs/03-arcus-spring-usage.md
> +일반적으로 `@Cacheable` 어노테이션을 사용하지만, 간혹 CacheManager를 주입 받아 직접 사용해야 하는 경우가 있다.
사용해야 하는 경우가 있다. => 사용할 수 있다.

2023-11-21 01:40 UTC, jhpark816 commented on docs/04-arcus-spring-notes.md
> +이러한 현상을 피하기 위해서는 SimpleStringKeyGenerator를 사용해야 한다.
SimpleStringKeyGenerator 사용할 경우 키 문자열에 공백(` `) 문자가 들어갈 수 있으며, 이 경우 ARCUS 연산이 정상 동작하지 않으므로 이를 주의해야 하고, Custom key generator 구현하여 사용할 수 있다는 내용이 어딘가에 들어가면 좋겠습니다.

2023-11-21 01:40 UTC, jhpark816 commented on docs/02-arcus-spring-concept.md
> +- `<serviceId><prefix | cacheName>:<stringOfKeyGenerator>`
이 내용은 아래 paragraph 아래로 옮기는 것이 좋을 것 같습니다.

아래에서는 여전히 subkey 문자열 생성에 대해 설명하는 것이며,
최종적으로 캐시 키가 prefix 문자열과 조합하여 만들어진다는 것이 마지막에 위치하는 것이 좋겠습니다.

2023-11-21 02:13 UTC, uhm0311 commented
@jhpark816 

리뷰 반영했습니다.

2023-11-21 02:23 UTC, merged