INTERNAL: get NullValue instance from arcus server
naver/arcus-spring pull request #78
Opened 2024-05-16 08:54 UTC by oliviarla

### 🔗 Related Issue

- https://github.com/jam2in/arcus-works/issues/541

### ⌨️ What I did

- ArcusCache 클래스가 AbstractValueAdaptingCache 클래스를 상속받도록 변경합니다. 이를 위해 lookup 메서드를 재정의했습니다.
- 이를 통해 NullValue 객체 조회 시 null을 반환해주는 AbstractValueAdaptingCache 클래스의 get 메서드가 ArcusCache에서 기본으로 사용되게 됩니다.
- ArcusCacheConfiguration 클래스에서는 cacheNullValues 속성을 설정할 수 있도록 합니다.
- 기존에 `get(Object key)` 메서드에서는 wantToGetException 속성이 유효했지만, 현재는 해당 설정이 무효하여 예외가 발생하면 그대로 전파됩니다.

2024-05-17 01:42 UTC, uhm0311 requested changes

2024-05-17 01:42 UTC, uhm0311 commented on src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
> +  private <T> T getValue(String arcusKey) throws Exception {
여기 반환 타입을 바꿀 필요가 있나요?

2024-05-17 01:42 UTC, uhm0311 commented on src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
> +    return value;
value 변수 없이 그냥 반환합시다.

2024-05-17 01:42 UTC, uhm0311 commented on src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
> +  }
Lock을 사용하는 범위가 달라졌습니다.
이 변경 사항은 NullValue 지원과는 다른 성격인 것 같으니 사전 PR로 먼저 반영하시죠.

2024-05-17 01:42 UTC, uhm0311 commented on src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
> -  public ValueWrapper get(Object key) {
이 메소드를 제거하겠단 뜻이었군요.
오버라이드해서 super.get(key)를 try-catch로 감싸고 wantToGetException에 따라 예외를 던질지 말지 결정합시다.
new SimpleValueWrapper()를 만들어서 반환하는 부분은 AbstractValueAdaptingCache.toValueWrapper() 메소드를 사용하면 됩니다.

2024-05-17 06:41 UTC, oliviarla commented
@uhm0311 리뷰 반영했습니다.

2024-05-17 06:51 UTC, uhm0311 requested changes

2024-05-17 06:51 UTC, uhm0311 commented on src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
> +    } catch (RuntimeException e) {
이 메소드를 직접 호출하는 응용 입장에선 인터페이스 변경이 없도록 합시다.
기존 메소드에서 try문 안에 super.get()을 호출하는 형태로 바꾸면 됩니다.

2024-05-17 07:04 UTC, oliviarla commented on src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
> +    } catch (RuntimeException e) {
인터페이스 변경이라 함이 구현의 형태가 변경되었다는 것을 의미하시는 건가요?
만약 그런 의미라고 한다면 저는 기존과 꼭 동일한 흐름이지는 않아도 된다고 생각했습니다.

2024-05-17 07:06 UTC, uhm0311 commented on src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
> +    } catch (RuntimeException e) {
RuntimeException만 잡고 있는 것을 의미했는데 다시 생각해보니 RuntimeException만 잡아도 되네뇨.

2024-05-17 07:10 UTC, uhm0311 commented on src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheTest.java
> +            .thenReturn(VALUE);
이걸 위로 올렸는데 그러지 않으면 테스트 통과가 안되나요?

2024-05-17 07:10 UTC, uhm0311 commented on src/main/java/com/navercorp/arcus/spring/cache/ArcusCacheConfiguration.java
> -
이 변경사항은 없어도 됩니다.

2024-05-20 01:43 UTC, oliviarla commented on src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheTest.java
> +            .thenReturn(VALUE);
테스트 통과와 상관은 없지만 메서드 흐름과 mock 흐름이 달라서 일치시키려 했던 것인데 , 다른 부분에도 흐름이 다른 부분이 많아  이 부분은 원상복구해두겠습니다.

2024-05-20 02:42 UTC, uhm0311 commented
@oliviarla 

allowNullValue 여부에 따라 null을 저장하려고 시도했을 때 성공/실패를 검증하는 테스트 코드도 추가해주세요.

2024-05-20 03:54 UTC, oliviarla commented
@uhm0311 
테스트 코드를 추가하기 위해 `NullValue.INSTANCE` 정적 필드를 이용해 객체를 가져오려고 했으나, 현재 spring 4.3.0 버전 기준으로는 package private 이므로 NullValue 객체를 생성할 수 없습니다.

spring 4.3.10 버전 이후부터는 public으로 바뀌었기 때문에 `NullValue.INSTANCE` 정적 필드를 사용할 수 있으나, 현재로서는 reflection을 통해서만 객체를 생성할 수 있습니다.

spring 패치 버전을 올리고 테스트 코드를 작성할 지, 아니면 reflection으로 작성해둘지 의견을 주시면 감사하겠습니다.

2024-05-20 10:40 UTC, uhm0311 approved these changes

2024-05-21 01:29 UTC, uhm0311 reviewed
https://github.com/spring-projects/spring-framework/blob/v4.3.0.RELEASE/spring-context/src/main/java/org/springframework/cache/support/AbstractValueAdaptingCache.java#L91-L102

이런 메소드가 있는데 NullValue 가져오기 위해 사용해보세요.

2024-05-21 01:33 UTC, jhpark816 reviewed
일부 리뷰

2024-05-21 01:33 UTC, jhpark816 commented on src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
> +      throw toRuntimeException(e);
lookup 메소드에서는 `wantToGetException` 설정에 따라 동작해야 하지 않는지?
lookup 메소드는 어떤 용도로 사용되나요?

2024-05-21 01:33 UTC, jhpark816 commented on src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
> +    return result != null ? (T) result.get() : getSynchronized(key, valueLoader);
아래 코딩 스타일이 어떤지?
```java
    ValueWrapper result = super.get(key);
    if (result != null) {
      return (T) result.get();
    }
    return getSynchronized(key, valueLoader);
```

2024-05-21 01:33 UTC, jhpark816 commented on src/main/java/com/navercorp/arcus/spring/cache/ArcusCacheConfiguration.java
> +  }
boolean 타입이라 아래 형태의 메소드 명이 나음
- isXXXX()
- setXXXX()

그리고, AllowCacheNullValues  보다 AllowNullValues로 하시죠.

2024-05-21 01:33 UTC, jhpark816 commented on src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
> +      return super.get(key);
`super.get(key)`은 어떻게 동작하나요?

2024-05-21 01:33 UTC, jhpark816 commented on src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
> +    } catch (RuntimeException e) {
Exception이 아니라 RuntimeException으로 변경한 이유는?

2024-05-21 01:33 UTC, jhpark816 commented on src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
> +        throw e;
info logging 제거한 이유는 ?

2024-05-21 02:32 UTC, oliviarla commented on src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
> +      throw toRuntimeException(e);
기존에 wantToGetException을 사용하던 메서드에서 처리하도록 했습니다.
lookup 메서드는 부모 클래스의 get 메서드에서 사용됩니다.

아래는 get 메서드이며, lookup 메서드를 통해 캐시 서버로부터 얻은 데이터를 NullValue를 고려하여 ValueWrapper 객체로 래핑하는 역할을 합니다.
```java
public Cache.ValueWrapper get(Object key) {
  Object value = this.lookup(key);
  return this.toValueWrapper(value);
}
```

2024-05-21 02:32 UTC, oliviarla commented on src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
> +    } catch (RuntimeException e) {
lookup 메서드에서 모든 예외를 RuntimeException으로 래핑하여 던지기 때문에 여기서는 오직 RuntimeException만 받게 됩니다.

2024-05-21 02:32 UTC, oliviarla commented on src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
> +    return result != null ? (T) result.get() : getSynchronized(key, valueLoader);
제 생각에는 result가 null인지에 따른 간단한 분기라서 삼항 연산자를 사용해도 괜찮을 것 같습니다.

2024-05-21 02:33 UTC, oliviarla commented
@uhm0311 
이미 테스트코드에서 reflection을 통해 protected 접근 제어자인 toStoreValue 메서드를 사용하고 있는데, 어떤 의미인가요?

2024-05-21 02:35 UTC, uhm0311 commented
@oliviarla 

리플렉션이나 4.3.10으로 업그레이드 하지 않고도 NullValue 접근이 가능하다면 시도해보라는 의미였습니다.
불가능하다면 4.3.10으로 업그레이드 하시죠.

2024-05-21 03:03 UTC, jhpark816 commented on src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
> +      throw toRuntimeException(e);
@oliviarla 
lookup() 호출하는 get() 메소드가 AbstractValueAdaptingCache 클래스에 구현되어 있다는 거죠?

2024-05-21 03:04 UTC, oliviarla commented on src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
> +      throw toRuntimeException(e);
네 맞습니다.

2024-05-21 03:07 UTC, uhm0311 approved these changes

2024-05-21 03:55 UTC, jhpark816 reviewed
리뷰 완료

2024-05-21 03:55 UTC, jhpark816 commented on src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
> +      acquireWriteLockOnKey(arcusKey);
`arcusKey` 대신에 `key` 사용하여도 문제되지 않을 것 같습니다.

2024-05-21 03:55 UTC, jhpark816 commented on src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
> -  public <T> T get(Object key, Class<T> type) {
아래 메소드도  wantToGetException 구현을 위해 override해야 하지 않는 지?
기존 구현에서 wantToGetException 추가하지 않았기 때문인가요?


```java
public <T> T get(Object key, Class<T> type)
```

2024-05-21 03:55 UTC, jhpark816 commented on src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
> +    } finally {
이 경우는 exception catch 하지 않아도 되나요?

2024-05-21 03:55 UTC, jhpark816 commented on src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheTest.java
> +            .asyncGet(arcusKey);
기존 코드와 비교하여, indentation 차이 있습니다.

2024-05-21 06:18 UTC, oliviarla commented on src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
> +    } finally {
acquireWriteLockOnKey 메서드 시그니처에 throws가 없기 때문에 catched exception은 발생하지 않습니다. 따라서 lock 획득 과정에서 발생한 exception을 catch하지 않아도 문제가 없습니다.

2024-05-21 06:29 UTC, jhpark816 commented on src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
> +      acquireWriteLockOnKey(arcusKey);
@oliviarla 
`key`로 변경해도 문제는 없는거죠?

@uhm0311 
위의 사항 검토 바랍니다.

2024-05-21 06:35 UTC, oliviarla commented on src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
> +      acquireWriteLockOnKey(arcusKey);
service id나 prefix를 덧붙이는 과정이 없기 때문에, 다른 service id, prefix에 같은 key가 존재하는 경우가 많다면 성능의 저하가 발생할 수 있지 않을까요?
ex) `BLOG:abc`, `SETTING:abc`, `FEED: abc`

2024-05-21 06:38 UTC, uhm0311 commented on src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
> +      acquireWriteLockOnKey(arcusKey);
@jhpark816 

key로 변경해도 기능상 버그는 없고 위와 같이 Prefix가 붙지 않아 서로 다른 캐시 키임에도 동일한 캐시 키로 판단할 수는 있습니다.
따라서 arcusKey를 사용하는 것이 맞습니다.

2024-05-21 06:42 UTC, uhm0311 commented on src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
> +
Empty Line 제거

2024-05-21 13:05 UTC, jhpark816 reviewed
리뷰 완료

2024-05-21 13:05 UTC, jhpark816 commented on src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
> +      acquireWriteLockOnKey(arcusKey);
lock 선택하기 위한 키로 `arcusKey` 사용하도록 하시죠. 
향후에 다시 검토할 만한 내용인 것 같습니다.

2024-05-22 01:32 UTC, oliviarla commented on src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
> +      return null;
저도 동일한 생각입니다. Exception이 던져지는 경우라면 스스로 로깅할 필요가 없습니다.

2024-05-22 01:35 UTC, oliviarla commented on src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
> +      throw toRuntimeException(e);
exception 로깅에 대한 처리 여부는 lookup 메서드가 아니라 get 메서드에서 wantToGetException 속성에 따라 처리하는게 나을 것 같습니다.

2024-05-22 02:16 UTC, uhm0311 approved these changes

2024-05-22 03:00 UTC, merged