INTERNAL: put NullValue instance to Arcus and frontCache
naver/arcus-spring pull request #93
Opened 2024-06-26 06:55 UTC by oliviarla

### 🔗 Related Issue

- https://github.com/jam2in/arcus-works/issues/541

### ⌨️ What I did

- put, putIfAbsent에서 NullValue를 저장하는 기능을 추가합니다.
- `getSynchrinozed(...)`에서 기존에는 createArcusKey의 결과인 String을 사용해 lock을 잡고 loadValue에도 넘겨 사용했었는데, 이런 방식으로는 같은 클래스의 public 메서드인 put을 사용할 수 없어 putValue를 직접 사용해야만 했습니다. 따라서 createArcusKey를 put 메서드 내부에서만 호출하게 하고 나머지 부분에서는 key를 그대로 사용하도록 하여 메서드 로직을 간결하게 만들었습니다.
- `putIfAbsent(...)` 에서 arcus java client API를 사용하는 부분을 따로 메서드로 분리했습니다.

2024-06-26 10:50 UTC, oliviarla commented
@uhm0311 리뷰 반영했습니다.

2024-06-27 04:50 UTC, uhm0311 requested changes

2024-06-27 04:50 UTC, uhm0311 commented on src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheIntegrationTest.java
> +import org.springframework.cache.support.SimpleValueWrapper;
쓰이지 않는다면 제거해주세요.

2024-06-27 04:50 UTC, uhm0311 commented on src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheIntegrationTest.java
> +    Cache.ValueWrapper result = arcusCache.get(TEST_KEY);
`assertNotNull(result)`도 해줍시다.

2024-06-27 04:50 UTC, uhm0311 commented on src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheIntegrationTest.java
> +  public void putTheNullValueIfAllowNullValuesIsTrue() {
`putTheNullValueIfAllowNullValuesIsFalse` 테스트는 없어도 되나요?

2024-06-27 05:50 UTC, oliviarla commented on src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheIntegrationTest.java
> +  public void putTheNullValueIfAllowNullValuesIsTrue() {
xml로 등록된 빈을 주입해온 ArcusCache를 사용하다보니 해당 테스트를 만들기 난감한 상황이라 일단은 추가하지 않았습니다.
reflection을 사용하거나 새로운 빈을 또 등록하는 방식밖에 떠오르지 않는데 어떤 방식이 나을까요??

2024-07-01 01:35 UTC, uhm0311 commented on src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheIntegrationTest.java
> +  public void putTheNullValueIfAllowNullValuesIsTrue() {
새로운 빈을 등록하는 것이 좋을 것 같습니다.

2024-07-01 07:53 UTC, oliviarla commented on src/test/java/com/navercorp/arcus/spring/cache/ArcusCacheIntegrationTest.java
> +  public void putTheNullValueIfAllowNullValuesIsTrue() {
추가했습니다.

2024-07-01 08:43 UTC, uhm0311 approved these changes

2024-07-04 02:32 UTC, oliviarla commented
@jhpark816 리뷰 부탁드립니다.

2024-07-05 02:26 UTC, jhpark816 reviewed
리뷰 완료

2024-07-05 02:26 UTC, jhpark816 commented on src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
> +    if (!isAllowNullValues() && value == null) {
아래의 조건 순서가 좋은 것 같습니다.
(value == null && !isAllowNullValues())

2024-07-05 02:26 UTC, jhpark816 commented on src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
> +    return putIfAbsentValue(key, toStoreValue(value));
다른 코드와의 일관성을 위해 아래 코드 형태가 낫지 않는 지 ?

```java
   String arcusKey = createArcusKey(key);
    try {
      return putIfAbsentValue(arcusKey, toStoreValue(value));
    } catch (Exception e) {
      if (wantToGetException) {
        throw toRuntimeException(e);
      }
      logger.info("failed to putIfAbsent. error: {}, key: {}", e.getMessage(), arcusKey);
      return super.get(key);
    }
```

2024-07-05 02:26 UTC, jhpark816 commented on src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
> +    return putIfAbsentValue(key, toStoreValue(value));
Null value 저장과 코드 리팩토링이 함께 있는 데요.
리팩토링 PR과  Null Value 저장 PR을 분리하는 것은 어떤가요 ?

2024-07-05 03:51 UTC, oliviarla commented on src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
> +    return putIfAbsentValue(key, toStoreValue(value));
리뷰 반영했습니다.

2024-07-05 09:23 UTC, jhpark816 commented
@uhm0311 리뷰 바랍니다.

2024-07-05 09:47 UTC, uhm0311 approved these changes

2024-07-05 09:53 UTC, merged

2024-07-05 09:54 UTC, jhpark816 commented
@oliviarla 
merge하고 나서 보니, master 브랜치에 올라간 것이네요.
다시 원복해야 할 것 같습니다.

2024-07-05 09:58 UTC, jhpark816 commented on src/main/java/com/navercorp/arcus/spring/cache/ArcusCache.java
> -    }
아. 그리고, loadValue()에서 putValue() 호출할 수 있어서,
loadValue()에서 put() 호출하는 형태로 변경하는 것까지 포함되어야 할 것 같습니다.

2024-07-05 09:58 UTC, uhm0311 commented
@jhpark816 

develop 브랜치로 커밋 옮겼습니다.